### ISSUE TITLE
Bug: Multiplayer can't load any survival map (tested with multiple users)

### ISSUE THREAD

**Issue by ismail-doitbig** [CnCNet/cncnet-yr-client-package#339]
![image](https://github.com/CnCNet/cncnet-yr-client-package/assets/89635383/6f3e2c75-9959-40f9-88c9-aff0d275c66f)

version 8.52.0

**Comment by CnCRAZER** [comment]
Do both players have the maps trying to be played listed under the survival game mode? There was an oversight in one of the previous updates that is hopefully fixed in future 8.53 release. 

If the map isn’t listed for both players try doing a forced update to ensure the map files are existent for both players.

**Comment by ismail-doitbig** [comment]
I've tried all maps under the "survival" category none load for the other player. 
I tried it today with one player and yesterday with another one. Standard category maps did work. 

honestly razer sucks but other than that they are nice maps

**Comment by CnCRAZER** [comment]
Is the issue still going since latest update?

**Comment by ismail-doitbig** [comment]
It's solved!
